### ISSUE TITLE
iOS CSS: strange behavior and corrupting page when changing style in the debugger

### ISSUE THREAD

**Issue by hbinkle** [inspectdev/inspect-issues#129]
Inspect version: 0.7.9
Electron: 15.3.4
OS version and architecture: win32 x64 10.0.19044
iOS Version: 15.2.1

Repro:
1. On the iPhone open a project like: https://zclcr.csb.app/
2. select the magenta filter row element:
![image](https://user-images.githubusercontent.com/51942180/151752690-478e360e-82fc-4767-9f70-21d5cc9af78f.png)
3. deselect the color by unchecking the checkbox:
![image](https://user-images.githubusercontent.com/51942180/151752811-813a1a50-a9b4-4af5-9d8a-71431aa1c602.png)

--> the page get's messed up:
![image](https://user-images.githubusercontent.com/51942180/151752541-9d203714-f6ed-46ad-9a9e-daa334669f4f.png)

**Comment by auchenberg** [comment]
@hbinkle Thanks for the report. Where are the styles located for these elements? Are these inline `<style>` tags?

**Comment by hbinkle** [comment]
@auchenberg it's an react SPA using MUI and webpack which creates the styles as style tags in the header of the html document:
![image](https://user-images.githubusercontent.com/51942180/151922443-94e8d4e9-db3f-4a3b-a065-9254259432d3.png)

You can easily reproduce the issue as described above.

**Comment by auchenberg** [comment]
Confirmed.

**Comment by auchenberg** [comment]
Notes: This is a problem with BrowserStack too, so something funky is going on

**Comment by auchenberg** [comment]
Note: My suspicion here is that this is something to do about how the CSS domain is composing the CSS properties list as a string, and how it's being inserted as an inline style sheet. Something to do with the style tag that gets weird, and some formatting here that breaks in the kit specifically.

**Comment by auchenberg** [comment]
# CSS Style Corruption When Editing Styles on iOS

## Overview

Investigate and fix the issue where toggling CSS properties in the DevTools Styles panel corrupts the page on iOS devices.

**GitHub Issue**: https://github.com/inspectdev/inspect-issues/issues/129

## Current State

- Toggling a CSS property checkbox corrupts the entire page styling
- Particularly affects React SPAs using MUI and CSS-in-JS libraries
- Styles are in inline `<style>` tags in the document head (created by webpack/MUI)
- Issue also reported on BrowserStack, suggesting WebKit-level problem

## Reproduction Steps

1. On iPhone, open a React/MUI app like https://zclcr.csb.app/
2. Select an element with applied styles (e.g., magenta filter row)
3. In Styles panel, uncheck a CSS property checkbox to disable it
4. Page styling becomes corrupted/messed up

## Investigation Findings

### 1. CSS Editing Flow

When a user toggles a CSS property:

```
User clicks checkbox
        │
        ▼
StylePropertyTreeElement._toggleDisabled(disabled)
        │
        ▼
CSSProperty.setDisabled(disabled)
  - Wraps property: "color: red;" → "/* color: red; */"
        │
        ▼
CSSProperty.setText(text, majorChange, overwrite)
  - Replaces property in full style text
  - Formats the new style text
        │
        ▼
CSSStyleDeclaration.setText(styleText, majorChange)
        │
        ▼
CSSModel.setStyleText(styleSheetId, range, text, majorChange)
        │
        ▼
CSS.setStyleTexts CDP command sent
        │
        ▼
iOS Adaptor: CSS.setStyleText (WebKit)
  - transformStyleSheetIdToStyleId() maps range to ordinal
  - Sends to WebKit
        │
        ▼
WebKit re-parses stylesheet and applies changes
```

### 2. iOS Adaptor Implementation

The adaptor converts CDP `CSS.setStyleTexts` to WebKit `CSS.setStyleText`:
```
```

### 3. Known WebKit Bug

**WebKit Bug 271403**: "Web Inspector: Glitches when trying to edit a style from a style sheet that has an @import statement"

**Root Cause**: WebKit's `CSS.setStyleText` used to re-parse the **entire stylesheet** when making any edit. This caused:

1. **Incorrect events**: Stylesheets with `@import` (or complex structures) would trigger erroneous `StyleSheetRemoved` and `StyleSheetAdded` events
2. **Edit reversion**: Re-parsing could revert previously applied edits
3. **Expensive re-renders**: Frontend treated these as "significant changes"

**WebKit Fix** (commit 227d5b): Use CSSOM to update style declarations directly, avoiding full stylesheet re-parsing.

**Status**: Fixed in WebKit trunk, but unclear which iOS version includes this fix.

### 4. MUI/CSS-in-JS Specifics

MUI and similar libraries create inline `<style>` tags in the document head:

```html
<head>
  <style data-emotion="css">
    .css-1abc123 { color: magenta; background: white; ... }
    .css-2def456 { display: flex; ... }
    /* Many more rules */
  </style>
</head>
```

When WebKit re-parses these stylesheets:
- All style rules may get new IDs
- The connection between rules and elements can break
- Previously applied styles may be lost or misapplied

### 5. Potential Issues in Adaptor

Several areas in the adaptor could contribute:

1. **Ordinal resolution** (`transformStyleSheetIdToStyleId`):
   - May return incorrect ordinal after stylesheet changes
   - Relies on `CSS.getAllStyleSheets` and `CSS.getStyleSheet` calls

2. **Event handling**:
   - `CSS.styleSheetChanged` event may cause frontend to refetch styles
   - If WebKit sends spurious `StyleSheetRemoved`/`StyleSheetAdded`, frontend state corrupts

3. **Style text formatting**:
   - The `text` parameter sent to WebKit may have formatting issues
   - Comment syntax for disabled properties may interact poorly with re-parsing

## Technical Analysis

### Why Inline `<style>` Tags Are Affected

| Stylesheet Type | Re-parsing Impact |
|-----------------|-------------------|
| External `.css` file | Lower impact - fewer rules typically |
| Inline `<style>` tag | High impact - many rules, all affected |
| CSS-in-JS (MUI, etc.) | Highest impact - hundreds of rules, dynamic |

### Comparison with Chrome

Chrome's `CSS.setStyleTexts` implementation:
- Uses incremental updates
- Doesn't re-parse entire stylesheet
- Maintains stable rule IDs

WebKit's (old) implementation:
- Re-parses entire stylesheet
- Rule IDs can change
- Can trigger cascade of events

## Recommendations

### Option 1: Verify WebKit Fix Version

Determine which iOS version includes the WebKit fix (bug 271403):
- Test on iOS 17, 18 to see if issue persists
- If fixed in recent iOS, document minimum version requirement

### Option 2: Workaround in Adaptor

If the issue persists, implement workarounds:

```typescript
// Potential workaround: Batch style changes to minimize re-parsing
private async setStyleTexts(msg: any): Promise<any> {
  const params: Protocol.CSS.SetStyleTextsRequest = msg.params;

  // Group edits by stylesheet to minimize re-parse operations
  const editsByStyleSheet = new Map<string, typeof params.edits>();

  for (const edit of params.edits) {
    const existing = editsByStyleSheet.get(edit.styleSheetId) || [];
    existing.push(edit);
    editsByStyleSheet.set(edit.styleSheetId, existing);
  }

  // Apply edits per stylesheet
  for (const [styleSheetId, edits] of editsByStyleSheet) {
    // Apply in reverse order to maintain correct ordinals
    for (const edit of edits.reverse()) {
      // ... apply edit
    }
  }
}
```

### Option 3: Alternative Approach Using setStyleSheetText

Instead of modifying individual styles, modify the entire stylesheet text:

1. Get current stylesheet text via `CSS.getStyleSheetText`
2. Apply text modifications locally
3. Set entire stylesheet via `CSS.setStyleSheetText`

This avoids the ordinal resolution issues but requires careful text manipulation.

### Option 4: Document Limitation

If no workaround is feasible:
- Document the limitation for CSS-in-JS libraries
- Recommend users test style changes on Chrome/Android instead
- Track WebKit bug for eventual fix

## Testing Plan

### Manual Testing

1. **Basic style toggle**:
   - Open simple HTML page with inline `<style>`
   - Toggle properties on/off
   - Verify page doesn't corrupt

2. **MUI/React app**:
   - Open https://zclcr.csb.app/ or similar
   - Toggle properties on multiple elements
   - Check for corruption

3. **External stylesheet**:
   - Test with page using external `.css` file
   - Verify editing works correctly

4. **iOS version matrix**:
   - Test on iOS 15, 16, 17, 18
   - Document which versions exhibit the bug

### Automated Testing

```typescript
// Test ordinal resolution
it('should resolve correct ordinal after stylesheet changes', async () => {
  // Add multiple rules to inline stylesheet
  // Modify one rule
  // Verify correct ordinal is resolved
  // Verify other rules are unaffected
});
```

## Implementation Phases

### Phase 1: Investigation
- [ ] Test on various iOS versions to identify which have the fix
- [ ] Add logging to track ordinal resolution and WebKit responses
- [ ] Capture network traffic to see exact CDP/WebKit messages

### Phase 2: Analysis
- [ ] Compare WebKit behavior across iOS versions
- [ ] Identify if adaptor or WebKit is primary cause
- [ ] Document specific scenarios that trigger corruption

### Phase 3: Fix (if applicable)
- [ ] Implement workaround if WebKit bug persists on supported iOS versions
- [ ] Test fix with MUI/CSS-in-JS apps
- [ ] Verify no regressions with external stylesheets

### Phase 4: Documentation
- [ ] Document any limitations
- [ ] Update minimum iOS version if fix requires newer iOS
- [ ] Add known issues to release notes if needed

## References

- **GitHub Issue**: https://github.com/inspectdev/inspect-issues/issues/129
- **WebKit Bug 271403**: https://bugs.webkit.org/show_bug.cgi?id=271403
- **WebKit Bug 150357**: https://bugs.webkit.org/show_bug.cgi?id=150357
- **WebKit Fix Commit**: https://www.mail-archive.com/webkit-changes@lists.webkit.org/msg219773.html
